## DATA CLEANING
- Date columns to datetime
- splitting indicators to better see all affecting indicators in the dataset
- pivoting and merging to show relationships
- saving the cleaned dataset

In [1]:
# LIB N DATA

import pandas as pd
import numpy as np

train = pd.read_csv(r'C:\Users\User\Desktop\credit-risk-project\data\raw\train.csv')
economic = pd.read_csv(r'C:\Users\User\Desktop\credit-risk-project\data\raw\economic_indicators.csv')

In [2]:
train.head()

,ID,customer_id,country_id,tbl_loan_id,lender_id,loan_type,Total_Amount,Total_Amount_to_Repay,disbursement_date,due_date,duration,New_versus_Repeat,Amount_Funded_By_Lender,Lender_portion_Funded,Lender_portion_to_be_repaid,target
0,ID_257244237466267278,257244,Kenya,237466,267278,Type_1,16477.0,16642.0,2022-08-15,2022-08-22,7,Repeat Loan,2436.0,0.147842,2460.0,0
1,ID_249619214444267278,249619,Kenya,214444,267278,Type_1,5599.0,5599.0,2022-07-13,2022-07-20,7,Repeat Loan,2799.5,0.500000,2800.0,0
2,ID_251457257838267278,251457,Kenya,257838,267278,Type_1,4679.0,4746.0,2022-09-12,2022-09-19,7,Repeat Loan,7.8,0.001667,8.0,0
3,ID_266224270337267278,266224,Kenya,270337,267278,Type_1,6123.0,6123.0,2022-09-29,2022-10-06,7,Repeat Loan,318.8,0.052066,319.0,0
4,ID_250369246185267278,250369,Kenya,246185,267278,Type_1,2953.0,2974.0,2022-08-27,2022-09-03,7,Repeat Loan,15.0,0.005080,15.0,0

In [3]:
# DATA TYPES N MISSING VALUES IN TRAIN
print("Data types:\n", train.dtypes)
print("\nMissing values:\n", train.isnull().sum())

Data types:
 ID                                 str
customer_id                      int64
country_id                         str
tbl_loan_id                      int64
lender_id                        int64
loan_type                          str
Total_Amount                   float64
Total_Amount_to_Repay          float64
disbursement_date                  str
due_date                           str
duration                         int64
New_versus_Repeat                  str
Amount_Funded_By_Lender        float64
Lender_portion_Funded          float64
Lender_portion_to_be_repaid    float64
target                           int64
dtype: object

Missing values:
 ID                             0
customer_id                    0
country_id                     0
tbl_loan_id                    0
lender_id                      0
loan_type                      0
Total_Amount                   0
Total_Amount_to_Repay          0
disbursement_date              0
due_date                       0
duration                       0
New_versus_Repeat              0
Amount_Funded_By_Lender        0
Lender_portion_Funded          0
Lender_portion_to_be_repaid    0
target                         0
dtype: int64

In [4]:
# DATE FORMATTING STR TO DATETIME
train['disbursement_date'] = pd.to_datetime(train['disbursement_date'])
train['due_date'] = pd.to_datetime(train['due_date'])
print(train[['disbursement_date', 'due_date']].dtypes)
print(train[['disbursement_date', 'due_date']].head())

disbursement_date    datetime64[us]
due_date             datetime64[us]
dtype: object
  disbursement_date   due_date
0        2022-08-15 2022-08-22
1        2022-07-13 2022-07-20
2        2022-09-12 2022-09-19
3        2022-09-29 2022-10-06
4        2022-08-27 2022-09-03

In [5]:
print("Data types:\n", train.dtypes)

Data types:
 ID                                        str
customer_id                             int64
country_id                                str
tbl_loan_id                             int64
lender_id                               int64
loan_type                                 str
Total_Amount                          float64
Total_Amount_to_Repay                 float64
disbursement_date              datetime64[us]
due_date                       datetime64[us]
duration                                int64
New_versus_Repeat                         str
Amount_Funded_By_Lender               float64
Lender_portion_Funded                 float64
Lender_portion_to_be_repaid           float64
target                                  int64
dtype: object

In [6]:
# DUPLICATE RECS
print("Duplicate rows:", train.duplicated().sum())
print("Duplicate loan IDs:", train['tbl_loan_id'].duplicated().sum())
print("Duplicate customer IDs:", train['customer_id'].duplicated().sum())

Duplicate rows: 0
Duplicate loan IDs: 2085
Duplicate customer IDs: 62137

In [7]:
economic.head()

,Country,Indicator,YR2001,YR2002,YR2003,YR2004,YR2005,YR2006,YR2007,YR2008,...,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023
0,Ghana,"Inflation, consumer prices (annual %)",41.509496,9.360932,29.772980,18.042739,15.438992,11.679184,10.734267,16.494640,...,15.489616,17.149970,17.454635,12.371922,7.808765,7.143640,9.887290,9.971089,31.255895,38.106966
1,Cote d'Ivoire,"Inflation, consumer prices (annual %)",4.361529,3.077265,3.296807,1.457988,3.885830,2.467191,1.892006,6.308528,...,0.448682,1.251500,0.723178,0.685881,0.359409,-1.106863,2.425007,4.091952,5.276167,4.387117
2,Kenya,"Inflation, consumer prices (annual %)",5.738598,1.961308,9.815691,11.624036,10.312778,14.453734,9.758880,26.239817,...,6.878155,6.582154,6.297250,8.005650,4.689806,5.239638,5.405162,6.107936,7.659863,7.671396
3,Ghana,"Official exchange rate (LCU per US$, period av...",0.716305,0.792417,0.866764,0.899495,0.905209,0.915107,0.932619,1.052275,...,2.896575,3.714642,3.909817,4.350533,4.585325,5.217367,5.595708,5.805700,8.272400,11.020408
4,Cote d'Ivoire,"Official exchange rate (LCU per US$, period av...",732.397693,693.713227,579.897426,527.338032,527.258363,522.425625,478.633718,446.000041,...,493.757330,591.211698,592.605615,580.656750,555.446458,585.911013,575.586004,554.530675,623.759701,606.569750

In [8]:
# RESHAPING ECON DATASET, (COLUMNS R YEARS)
economic_melted = economic.melt(
    id_vars=['Country', 'Indicator'],
    var_name='Year',
    value_name='Value'
)
economic_melted['Year'] = economic_melted['Year'].str.replace('YR', '').astype(int)
print(economic_melted.shape)
economic_melted.head(10)

(621, 4)

,Country,Indicator,Year,Value
0,Ghana,"Inflation, consumer prices (annual %)",2001,41.509496
1,Cote d'Ivoire,"Inflation, consumer prices (annual %)",2001,4.361529
2,Kenya,"Inflation, consumer prices (annual %)",2001,5.738598
3,Ghana,"Official exchange rate (LCU per US$, period av...",2001,0.716305
4,Cote d'Ivoire,"Official exchange rate (LCU per US$, period av...",2001,732.397693
5,Kenya,"Official exchange rate (LCU per US$, period av...",2001,78.563195
6,Ghana,Real interest rate (%),2001,NaN
7,Cote d'Ivoire,Real interest rate (%),2001,NaN
8,Kenya,Real interest rate (%),2001,17.812501
9,Ghana,Average precipitation in depth (mm per year),2001,1187.000000

In [ ]:
# PIVOT ECONOMIC DATASET SO EACH INDICATOR IS A COLUMN(i.e: inflation, consumer prices, Real interest rate, unemployment rate etc)
economic_pivot = economic_melted.pivot_table(
    index=['Country', 'Year'],
    columns='Indicator',
    values='Value'
).reset_index()
economic_pivot.columns.name = None
print(economic_pivot.shape)
economic_pivot.head()

(69, 11)

,Country,Year,Average precipitation in depth (mm per year),Deposit interest rate (%),Fossil fuel energy consumption (% of total),"Inflation, consumer prices (annual %)","Interest rate spread (lending rate minus deposit rate, %)",Lending interest rate (%),"Official exchange rate (LCU per US$, period average)",Real interest rate (%),Unemployment rate
0,Cote d'Ivoire,2001,1348.0,NaN,34.298397,4.361529,NaN,NaN,732.397693,NaN,5.199
1,Cote d'Ivoire,2002,1348.0,NaN,37.848716,3.077265,NaN,NaN,693.713227,NaN,5.516
2,Cote d'Ivoire,2003,1348.0,NaN,32.501441,3.296807,NaN,NaN,579.897426,NaN,5.858
3,Cote d'Ivoire,2004,1348.0,NaN,24.930573,1.457988,NaN,NaN,527.338032,NaN,5.930
4,Cote d'Ivoire,2005,1348.0,7.6075,25.391257,3.885830,-0.558333,7.049167,527.258363,5.763991,6.041

In [11]:
# Extract year from train to merge on
train['loan_year'] = train['disbursement_date'].dt.year
print(train['loan_year'].value_counts().sort_index())

loan_year
2021       37
2022    64491
2023     1197
2024     2929
Name: count, dtype: int64

In [12]:
# PROCESSED DATA
train.to_csv(r'C:\Users\User\Desktop\credit-risk-project\data\processed\train_cleaned.csv', index=False)
economic_pivot.to_csv(r'C:\Users\User\Desktop\credit-risk-project\data\processed\economic_pivot.csv', index=False)
print("Saved successfully")

Saved successfully