## FEATURE ENGINEERING

In [1]:
import pandas as pd
import numpy as np

train = pd.read_csv(r'C:\Users\User\Desktop\credit-risk-project\data\processed\train_cleaned.csv', parse_dates=['disbursement_date', 'due_date'])

In [2]:
train.head()

,ID,customer_id,country_id,tbl_loan_id,lender_id,loan_type,Total_Amount,Total_Amount_to_Repay,disbursement_date,due_date,duration,New_versus_Repeat,Amount_Funded_By_Lender,Lender_portion_Funded,Lender_portion_to_be_repaid,target,loan_year
0,ID_257244237466267278,257244,Kenya,237466,267278,Type_1,16477.0,16642.0,2022-08-15,2022-08-22,7,Repeat Loan,2436.0,0.147842,2460.0,0,2022
1,ID_249619214444267278,249619,Kenya,214444,267278,Type_1,5599.0,5599.0,2022-07-13,2022-07-20,7,Repeat Loan,2799.5,0.500000,2800.0,0,2022
2,ID_251457257838267278,251457,Kenya,257838,267278,Type_1,4679.0,4746.0,2022-09-12,2022-09-19,7,Repeat Loan,7.8,0.001667,8.0,0,2022
3,ID_266224270337267278,266224,Kenya,270337,267278,Type_1,6123.0,6123.0,2022-09-29,2022-10-06,7,Repeat Loan,318.8,0.052066,319.0,0,2022
4,ID_250369246185267278,250369,Kenya,246185,267278,Type_1,2953.0,2974.0,2022-08-27,2022-09-03,7,Repeat Loan,15.0,0.005080,15.0,0,2022

In [3]:
# FINANCIAL FEATURES i.e interest, ratio of repayment n lender profit
train['interest_amount'] = train['Total_Amount_to_Repay'] - train['Total_Amount']
train['repayment_ratio'] = train['Total_Amount_to_Repay'] / train['Total_Amount']
train['lender_profit'] = train['Lender_portion_to_be_repaid'] - train['Amount_Funded_By_Lender']

In [4]:
# DATE FEATURES i.e loan month, loan day of the week n loar quater of the yr
train['loan_month'] = train['disbursement_date'].dt.month
train['loan_dayofweek'] = train['disbursement_date'].dt.dayofweek
train['loan_quarter'] = train['disbursement_date'].dt.quarter

In [5]:
# LOAN FREQUENCY - loan counts throughout the dataset
loan_counts = train.groupby('customer_id')['tbl_loan_id'].count().reset_index()
loan_counts.columns = ['customer_id', 'customer_loan_count']
train = train.merge(loan_counts, on='customer_id', how='left')

In [ ]:
# DROP REDUNDANT/REPETITIVE COLUMNS
drop_cols = ['ID', 'country_id', 'Total_Amount_to_Repay', 'Lender_portion_to_be_repaid', 'disbursement_date', 'due_date']
train = train.drop(columns=drop_cols)
print(train.shape)
print(train.columns.tolist())

(68654, 18)
['customer_id', 'tbl_loan_id', 'lender_id', 'loan_type', 'Total_Amount', 'duration', 'New_versus_Repeat', 'Amount_Funded_By_Lender', 'Lender_portion_Funded', 'target', 'loan_year', 'interest_amount', 'repayment_ratio', 'lender_profit', 'loan_month', 'loan_dayofweek', 'loan_quarter', 'customer_loan_count']

In [ ]:
# ENCODING CATEGORICALS - DUMMIES - HOTENCODER
# Categorical text data into numericals - transform loan type n new vs repeat. Dropping first category for each column,
# 2 possible type to give back one column 0 n 1 to rep
train = pd.get_dummies(train, columns=['loan_type', 'New_versus_Repeat'], drop_first=True)
print(train.shape) # number of added features
print(train.dtypes) # verify

(68654, 35)
customer_id                        int64
tbl_loan_id                        int64
lender_id                          int64
Total_Amount                     float64
duration                           int64
Amount_Funded_By_Lender          float64
Lender_portion_Funded            float64
target                             int64
loan_year                          int64
interest_amount                  float64
repayment_ratio                  float64
lender_profit                    float64
loan_month                         int32
loan_dayofweek                     int32
loan_quarter                       int32
customer_loan_count                int64
loan_type_Type_10                   bool
loan_type_Type_11                   bool
loan_type_Type_12                   bool
loan_type_Type_13                   bool
loan_type_Type_14                   bool
loan_type_Type_15                   bool
loan_type_Type_16                   bool
loan_type_Type_17                   bool
loan_type_Type_18                   bool
loan_type_Type_19                   bool
loan_type_Type_2                    bool
loan_type_Type_20                   bool
loan_type_Type_21                   bool
loan_type_Type_4                    bool
loan_type_Type_5                    bool
loan_type_Type_6                    bool
loan_type_Type_7                    bool
loan_type_Type_9                    bool
New_versus_Repeat_Repeat Loan       bool
dtype: object

In [8]:
# SAVE FEATURES
train.to_csv(r'C:\Users\User\Desktop\credit-risk-project\data\processed\train_features.csv', index=False)
print("Saved successfully")

Saved successfully

In [9]:
train.head()

,customer_id,tbl_loan_id,lender_id,Total_Amount,duration,Amount_Funded_By_Lender,Lender_portion_Funded,target,loan_year,interest_amount,...,loan_type_Type_19,loan_type_Type_2,loan_type_Type_20,loan_type_Type_21,loan_type_Type_4,loan_type_Type_5,loan_type_Type_6,loan_type_Type_7,loan_type_Type_9,New_versus_Repeat_Repeat Loan
0,257244,237466,267278,16477.0,7,2436.0,0.147842,0,2022,165.0,...,False,False,False,False,False,False,False,False,False,True
1,249619,214444,267278,5599.0,7,2799.5,0.500000,0,2022,0.0,...,False,False,False,False,False,False,False,False,False,True
2,251457,257838,267278,4679.0,7,7.8,0.001667,0,2022,67.0,...,False,False,False,False,False,False,False,False,False,True
3,266224,270337,267278,6123.0,7,318.8,0.052066,0,2022,0.0,...,False,False,False,False,False,False,False,False,False,True
4,250369,246185,267278,2953.0,7,15.0,0.005080,0,2022,21.0,...,False,False,False,False,False,False,False,False,False,True